/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiHelloRouteImport } from './routes/api/hello'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppPostsRouteRouteImport } from './routes/_app/posts/route'
import { Route as AppPostsIndexRouteImport } from './routes/_app/posts/index'
import { Route as ApiV2FooRouteImport } from './routes/api/v2/foo'
import { Route as ApiV2BarRouteImport } from './routes/api/v2/bar'
import { Route as ApiV1FooRouteImport } from './routes/api/v1/foo'
import { Route as ApiV1BarRouteImport } from './routes/api/v1/bar'
import { Route as AppPostsSlugRouteImport } from './routes/_app/posts/$slug'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiHelloRoute = ApiHelloRouteImport.update({
  id: '/api/hello',
  path: '/api/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppPostsRouteRoute = AppPostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AppRoute,
} as any)
const AppPostsIndexRoute = AppPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPostsRouteRoute,
} as any)
const ApiV2FooRoute = ApiV2FooRouteImport.update({
  id: '/api/v2/foo',
  path: '/api/v2/foo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV2BarRoute = ApiV2BarRouteImport.update({
  id: '/api/v2/bar',
  path: '/api/v2/bar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1FooRoute = ApiV1FooRouteImport.update({
  id: '/api/v1/foo',
  path: '/api/v1/foo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BarRoute = ApiV1BarRouteImport.update({
  id: '/api/v1/bar',
  path: '/api/v1/bar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPostsSlugRoute = AppPostsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppPostsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/posts': typeof AppPostsRouteRouteWithChildren
  '/$': typeof AppSplatRoute
  '/api/hello': typeof ApiHelloRoute
  '/posts/$slug': typeof AppPostsSlugRoute
  '/api/v1/bar': typeof ApiV1BarRoute
  '/api/v1/foo': typeof ApiV1FooRoute
  '/api/v2/bar': typeof ApiV2BarRoute
  '/api/v2/foo': typeof ApiV2FooRoute
  '/posts/': typeof AppPostsIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof AppSplatRoute
  '/api/hello': typeof ApiHelloRoute
  '/': typeof AppIndexRoute
  '/posts/$slug': typeof AppPostsSlugRoute
  '/api/v1/bar': typeof ApiV1BarRoute
  '/api/v1/foo': typeof ApiV1FooRoute
  '/api/v2/bar': typeof ApiV2BarRoute
  '/api/v2/foo': typeof ApiV2FooRoute
  '/posts': typeof AppPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/posts': typeof AppPostsRouteRouteWithChildren
  '/_app/$': typeof AppSplatRoute
  '/api/hello': typeof ApiHelloRoute
  '/_app/': typeof AppIndexRoute
  '/_app/posts/$slug': typeof AppPostsSlugRoute
  '/api/v1/bar': typeof ApiV1BarRoute
  '/api/v1/foo': typeof ApiV1FooRoute
  '/api/v2/bar': typeof ApiV2BarRoute
  '/api/v2/foo': typeof ApiV2FooRoute
  '/_app/posts/': typeof AppPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/posts'
    | '/$'
    | '/api/hello'
    | '/posts/$slug'
    | '/api/v1/bar'
    | '/api/v1/foo'
    | '/api/v2/bar'
    | '/api/v2/foo'
    | '/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/api/hello'
    | '/'
    | '/posts/$slug'
    | '/api/v1/bar'
    | '/api/v1/foo'
    | '/api/v2/bar'
    | '/api/v2/foo'
    | '/posts'
  id:
    | '__root__'
    | '/_app'
    | '/_app/posts'
    | '/_app/$'
    | '/api/hello'
    | '/_app/'
    | '/_app/posts/$slug'
    | '/api/v1/bar'
    | '/api/v1/foo'
    | '/api/v2/bar'
    | '/api/v2/foo'
    | '/_app/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiHelloRoute: typeof ApiHelloRoute
  ApiV1BarRoute: typeof ApiV1BarRoute
  ApiV1FooRoute: typeof ApiV1FooRoute
  ApiV2BarRoute: typeof ApiV2BarRoute
  ApiV2FooRoute: typeof ApiV2FooRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/hello': {
      id: '/api/hello'
      path: '/api/hello'
      fullPath: '/api/hello'
      preLoaderRoute: typeof ApiHelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/posts': {
      id: '/_app/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AppPostsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/posts/': {
      id: '/_app/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof AppPostsIndexRouteImport
      parentRoute: typeof AppPostsRouteRoute
    }
    '/api/v2/foo': {
      id: '/api/v2/foo'
      path: '/api/v2/foo'
      fullPath: '/api/v2/foo'
      preLoaderRoute: typeof ApiV2FooRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v2/bar': {
      id: '/api/v2/bar'
      path: '/api/v2/bar'
      fullPath: '/api/v2/bar'
      preLoaderRoute: typeof ApiV2BarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/foo': {
      id: '/api/v1/foo'
      path: '/api/v1/foo'
      fullPath: '/api/v1/foo'
      preLoaderRoute: typeof ApiV1FooRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/bar': {
      id: '/api/v1/bar'
      path: '/api/v1/bar'
      fullPath: '/api/v1/bar'
      preLoaderRoute: typeof ApiV1BarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/posts/$slug': {
      id: '/_app/posts/$slug'
      path: '/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof AppPostsSlugRouteImport
      parentRoute: typeof AppPostsRouteRoute
    }
  }
}

interface AppPostsRouteRouteChildren {
  AppPostsSlugRoute: typeof AppPostsSlugRoute
  AppPostsIndexRoute: typeof AppPostsIndexRoute
}

const AppPostsRouteRouteChildren: AppPostsRouteRouteChildren = {
  AppPostsSlugRoute: AppPostsSlugRoute,
  AppPostsIndexRoute: AppPostsIndexRoute,
}

const AppPostsRouteRouteWithChildren = AppPostsRouteRoute._addFileChildren(
  AppPostsRouteRouteChildren,
)

interface AppRouteChildren {
  AppPostsRouteRoute: typeof AppPostsRouteRouteWithChildren
  AppSplatRoute: typeof AppSplatRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPostsRouteRoute: AppPostsRouteRouteWithChildren,
  AppSplatRoute: AppSplatRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiHelloRoute: ApiHelloRoute,
  ApiV1BarRoute: ApiV1BarRoute,
  ApiV1FooRoute: ApiV1FooRoute,
  ApiV2BarRoute: ApiV2BarRoute,
  ApiV2FooRoute: ApiV2FooRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
